-- Distritos de Lima (Ejemplo inicial con algunos)
create table distritos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  zona text, -- Norte, Sur, Centro, Este, Oeste
  coordenadas_centro point -- Latitud, Longitud aproximada
);

-- Tabla principal de Colegios
create table colegios (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  slug text unique not null, -- Para URLs amigables (ej. /colegios/san-agustin)
  direccion text,
  distrito_id bigint references distritos(id),
  coordenadas point, -- Latitud, Longitud
  tipo text check (tipo in ('Privado', 'Público', 'Concertado')),
  mensualidad_min numeric,
  mensualidad_max numeric,
  matricula numeric,
  cuota_ingreso numeric,
  rating_promedio numeric default 0,
  fotos text[], -- Array de URLs de Cloudinary
  telefono text,
  email text,
  web text,
  google_maps_url text
);

-- Usuarios (Extiende la tabla auth.users de Supabase)
create table public.usuarios (
  id uuid references auth.users not null primary key,
  nombre_completo text,
  telefono text,
  preferencias jsonb -- Guardar filtros favoritos o configuración
);

-- Trigger para crear usuario público automáticamente al registrarse
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.usuarios (id, nombre_completo, telefono)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'phone');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Reselas y Opiniones
create table resenas (
  id bigint generated by default as identity primary key,
  colegio_id bigint references colegios(id) not null,
  usuario_id uuid references public.usuarios(id) not null,
  rating smallint check (rating >= 1 and rating <= 5),
  comentario text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Favoritos
create table favoritos (
  usuario_id uuid references public.usuarios(id) not null,
  colegio_id bigint references colegios(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (usuario_id, colegio_id)
);

-- RLS (Row Level Security) Policies - Básico
alter table colegios enable row level security;
create policy "Colegios visibles para todos" on colegios for select using (true);

alter table distritos enable row level security;
create policy "Distritos visibles para todos" on distritos for select using (true);

alter table resenas enable row level security;
create policy "Reseñas visibles para todos" on resenas for select using (true);
create policy "Usuarios pueden crear reseñas" on resenas for insert with check (auth.uid() = usuario_id);

alter table favoritos enable row level security;
create policy "Usuarios ven sus favoritos" on favoritos for select using (auth.uid() = usuario_id);
create policy "Usuarios gestionan sus favoritos" on favoritos for all using (auth.uid() = usuario_id);
